### ISSUE TITLE
whitespaces are too bright

### ISSUE THREAD

**Issue by sfr** [y3sh/Intellij-Colors-Sublime-Monokai#11]
Hi,

whitespaces are too bright. It is especially visible on tabs:
![whitespaces too bright](https://cloud.githubusercontent.com/assets/2040557/5510989/61193772-8796-11e4-9e13-c567937a514b.png)

Regards,
    Juraj.

**Comment by y3sh** [comment]
From the look of your font are you on Windows/Linux? In Intellij 14 on OS X, the whitespaces look like:

![screen shot 2015-01-24 at 1 12 40 pm](https://cloud.githubusercontent.com/assets/1032983/5888590/ce8a2140-a3ca-11e4-8fa8-1906412eb619.png)

I don't want to change the whitespaces for all users, but you can change them in your settings at: 

![screen shot 2015-01-24 at 1 12 27 pm](https://cloud.githubusercontent.com/assets/1032983/5888592/f5c4c332-a3ca-11e4-8029-8355bd836201.png)

**Comment by LoganDark** [comment]
@y3sh you do realize sane people use tabs instead of spaces, right? Just because your 1px dots aren't killing your eyes doesn't mean huge tab symbols won't kill anyone else's.

This is obviously a 3 y/o issue, and nothing's going to be changed, but I'm just offering my opinion since I found this in google search results. :>
