### ISSUE TITLE
Not Working with latest version of Intellij 2016.1

### ISSUE THREAD

**Issue by sajanlamsal** [y3sh/Intellij-Colors-Sublime-Monokai#20]

**Comment by y3sh** [comment]
At first glance it looks like just Java may need some tweaking. Can you describe what's not working for you? 

![image](https://cloud.githubusercontent.com/assets/1032983/14393065/734b5d42-fd8a-11e5-9245-f9620fd1f6fb.png)

**Comment by lxw0109** [comment]
@sajanlamsal 
At the beginning, it did not work for me either. And the error message is as follows:</br>
`....Please make sure you have generated the file using 'File|Export Settings' feature.`</br>
So I tried to import the whole directory instead of only the `SublimeMonoKai.jar` file, it said `cannot find the settings.jar file`.</br>
So I renamed the `SublimeMonoKai.jar` as `settings.jar`, now it works.</br>
May it help you. : )

**Comment by y3sh** [comment]
Thanks for the workaround!
